### ISSUE TITLE
'AuthResult' can't be assigned to a variable of type 'FirebaseUser'.

### ISSUE THREAD

**Issue by nikitwei** [mohak1283/chat-app-flutter#2]
hi this project is awesome.
im new with flutter and just try your project. and there is an error with home_page.dart at line 30 (A value of type 'AuthResult' can't be assigned to a variable of type 'FirebaseUser').
can you help me?

**Comment by nikitwei** [comment]
hei i found the answer. its because the [firebase_auth](https://pub.dev/packages/firebase_auth) plugin was change.
`   FirebaseUser user = (await _firebaseAuth.signInWithCredential(authCredential)).user;
    print("signed in " + user.displayName);
    return user;`

**Comment by haris96tz** [comment]
Hi nikitwei,
Did you manage to log in using your google account?

**Comment by apoorvlodhi-io** [comment]
Hey @nikitwei  @haris96tz 
Did you manage to log in using your google account?
